### ISSUE TITLE
how can we get datasets?

### ISSUE THREAD

**Issue by HongChow** [ArminKaramzade/im2latex#1]
hi, 
   Thanks to Pytroch Version.
   Where could I get the datasets?

**Comment by ArminKmz** [comment]
You can use [this](https://zenodo.org/record/56198#.XXQS3C2B10t) dataset, But you should add necessary modification to data or code to work with the dataset. Compatible dataset format is as follow:

images directory: .png files with names like "0.png", "1.png", ...
formulas: .txt file contains formula for "i.png" in its i-th row

Also note that all images should have same size.

**Comment by mtyrolski** [comment]
@ArminKaramzade it would be great if it was in readme.
